"""Init Database

Revision ID: a2267206e352
Revises: 
Create Date: 2020-06-11 16:33:21.310558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a2267206e352"
down_revision = None
branch_labels = ("default",)
depends_on = None


def upgrade():
    op.create_table(
        "cards",
        sa.Column("id", sa.String(length=130), nullable=False),
        sa.Column("name", sa.String(length=130), nullable=True),
        sa.Column("mana_cost", sa.String(length=100), nullable=True),
        sa.Column("cmc", sa.DECIMAL(precision=3, scale=1), nullable=True),
        sa.Column("type_line", sa.String(length=100), nullable=True),
        sa.Column(
            "card_type",
            sa.Enum(
                "Creature",
                "Artifact",
                "Enchantment",
                "Instant",
                "Land",
                "Sorcery",
                name="cardtype",
            ),
            nullable=True,
        ),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column(
            "rarity",
            sa.Enum("common", "uncommon", "rare", "mythic", name="rarity"),
            nullable=True,
        ),
        sa.Column("edhrec", sa.BigInteger(), nullable=True),
        sa.Column("color_identity", sa.String(length=50), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "decks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=True),
        sa.Column("date_created", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "deck_cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.String(length=130), nullable=False),
        sa.Column("deck_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"],),
        sa.ForeignKeyConstraint(["deck_id"], ["decks.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deck_cards")
    op.drop_table("decks")
    op.drop_table("cards")
    # ### end Alembic commands ###
