"""Init Database

Revision ID: c4d4c5e909db
Revises: 
Create Date: 2020-06-11 17:41:54.702316

"""
from alembic import op
import sqlalchemy as sa

import api


# revision identifiers, used by Alembic.
revision = "c4d4c5e909db"
down_revision = None
branch_labels = ("default",)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cards",
        sa.Column("id", sa.String(length=130), nullable=False),
        sa.Column("name", sa.String(length=130), nullable=True),
        sa.Column("mana_cost", sa.String(length=100), nullable=True),
        sa.Column("cmc", sa.DECIMAL(precision=3, scale=1), nullable=True),
        sa.Column("type_line", sa.String(length=100), nullable=True),
        sa.Column(
            "card_type",
            sa.Enum(
                "Creature",
                "Artifact",
                "Enchantment",
                "Instant",
                "Land",
                "Sorcery",
                name="cardtype",
            ),
            nullable=True,
        ),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column(
            "rarity",
            sa.Enum("common", "uncommon", "rare", "mythic", name="rarity"),
            nullable=True,
        ),
        sa.Column("edhrec", sa.BigInteger(), nullable=True),
        sa.Column("color_identity", api.models.PythonList(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "decks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=True),
        sa.Column("date_created", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "deck_cards",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("card_id", sa.String(length=130), nullable=False),
        sa.Column("deck_id", sa.String(length=36), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"],),
        sa.ForeignKeyConstraint(["deck_id"], ["decks.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deck_cards")
    op.drop_table("decks")
    op.drop_table("cards")
    # ### end Alembic commands ###
